### PR TITLE
Project Library: Add and Display Books using LocalStorage.

### PR DESCRIPTION
**Pull request by Abhigyan001**
- It has a form to add more books.
- The book attributes are: title, author, number of pages, has been read.
- Displays the list of books in card formation.
- The cards show all the information of each book, also has a button to toggle the value of "has been read" and another button to delete the book.
-The 'Add Book' button at the top of the page can toggle the visibility of the form.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Abhigyan001 and @ClaytonSiby 
### You have done well so far :clap: However, you have a few issues to fix:-
- [ ] We recommend the use of es6 arrow functions rather than the keyword function. See below
```
const displayBooks = () => { 
  # code
}
```
- [ ] There are errors with linting both the eslint and stylelint. Install all the required dependencies, configure them and run the commands npx `eslint .` and `npx stylelint "**/*.{css,scss}"` respectively in case of error kindly solve them. See the image below
linting
### Make the changes and submit the project for another review. Good luck.
- Happy coding!

**Review by rOluochKe — APPROVED** [review]
### You got it right, well done. The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Comment by ClaytonSiby** [comment]
Hi @rOluochKe thanks for the feedback & project approval. However, from my dashboard, the project is marked *Changes Required*, won't that be a problem if I submit it like that?

**Comment by Abhigyan001** [comment]
Hi, @rOluochKe thanks for the feedback. I am also facing the same issue as my partner @ClaytonSiby.

**Pull request merged**
